spring:
  datasource:
    url: #[jdbc:mariadb://{address}:{port}/{database}]
    username: #{user}
    password: #{password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: WARN
    me.aidimirov.jwtauth: DEBUG
auth:
  jwt:
    secret: #'{secret}'
    #Срок действия токенов указывать в минутах
    expiration:
      access_token: 5
      refresh_token: 10
